name: Pull Request
on:
  pull_request:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Setup Node.js
          uses: actions/setup-node@v1
          with:
              node-version: '18'
              cache: 'pnpm'
        - name: Install dependencies
          run: pnpm install
        - name: Run tests
          run: pnpm test:all
        - name: Run changeset
          run: pnpm changeset status
